version: "3.9"
services:
  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - GENERIC_TIMEZONE=UTC
      - DB_TYPE=redis
      - DB_REDIS_HOST=redis
      - DB_REDIS_PORT=6379
    depends_on: [redis]
    volumes: [ "n8n_data:/home/node/.n8n" ]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes: [ "qdrant_data:/qdrant/storage" ]

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
    ports: ["7700:7700"]
    volumes: ["meili_data:/meili_data"]

  temporal:
    image: temporalio/auto-setup:latest
    environment: [ "DB=sqlite" ]
    ports: ["7233:7233"]

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=langfuse
      - POSTGRES_USER=langfuse
      - POSTGRES_DB=langfuse
    volumes: [ "pg_data:/var/lib/postgresql/data" ]

  langfuse:
    image: langfuse/langfuse:latest
    depends_on: [postgres]
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
      - NEXTAUTH_SECRET=devsecret
      - SALT=devsalt
      - NEXTAUTH_URL=http://localhost:3000

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ "ollama_data:/root/.ollama" ]

  autoagent-core:
    build: ../apps/autoagent-core
    depends_on: [n8n, qdrant, meilisearch, temporal, langfuse, ollama]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
      - TEMPORAL_HOST=temporal:7233
      - PORT=8080
    volumes:
      - ../apps/autoagent-core:/app
      - ../core:/core
      - ../plugins:/plugins
      - ../data:/data
    ports: ["8080:8080"]
    command: bash -lc "pip install -e . && uvicorn app.main:app --host 0.0.0.0 --port 8080"

  nodered:
    image: nodered/node-red
    ports: ["1880:1880"]
    environment:
      - MQTT_BROKER=redis://redis:6379
    depends_on: [redis]

  scheduler:
    image: prefecthq/prefect:latest
    command: prefect agent start -q default
    volumes:
      - ../flows:/flows
    depends_on: [redis]

  python-ml:
    build: ../services/python-ml
    ports: ["5001:5001"]
    volumes:
      - ../data:/data
      - ~/.cache:/root/.cache
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on: [redis]

  odoo:
    image: odoo:15
    ports: ["8069:8069"]
    volumes:
      - odoo_data:/var/lib/odoo

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql

  wp:
    image: wordpress:php8.0-fpm-alpine
    ports: ["8081:80"]
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_CONFIG_EXTRA: |
        define('JWT_AUTH_SECRET_KEY', 'changeme');
    depends_on: [mariadb]
    volumes:
      - wp_plugins:/var/www/html/wp-content/plugins

  mautic:
    image: mautic/mautic:latest
    ports: ["8082:80"]
    depends_on: [mariadb]
    volumes:
      - mautic_data:/var/www/html

  temporal-worker:
    build: ../services/temporal-worker
    depends_on: [temporal]
    environment:
      - TEMPORAL_HOST=temporal:7233
    volumes:
      - ..:/workspace

volumes:
  n8n_data:
  qdrant_data:
  meili_data:
  pg_data:
  ollama_data:
  odoo_data:
  mariadb_data:
  wp_plugins:
  mautic_data:
