version: "3.9"
services:
  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment: [ "GENERIC_TIMEZONE=UTC" ]
    volumes: [ "n8n_data:/home/node/.n8n" ]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes: [ "qdrant_data:/qdrant/storage" ]

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
    ports: ["7700:7700"]
    volumes: ["meili_data:/meili_data"]

  temporal:
    image: temporalio/auto-setup:latest
    environment: [ "DB=sqlite" ]
    ports: ["7233:7233"]

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=langfuse
      - POSTGRES_USER=langfuse
      - POSTGRES_DB=langfuse
    volumes: [ "pg_data:/var/lib/postgresql/data" ]

  langfuse:
    image: langfuse/langfuse:latest
    depends_on: [postgres]
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
      - NEXTAUTH_SECRET=devsecret
      - SALT=devsalt
      - NEXTAUTH_URL=http://localhost:3000

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ "ollama_data:/root/.ollama" ]

  autoagent-core:
    build: ../apps/autoagent-core
    depends_on: [n8n, qdrant, meilisearch, temporal, langfuse, ollama]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
      - TEMPORAL_HOST=temporal:7233
      - PORT=8080
    volumes:
      - ../apps/autoagent-core:/app
      - ../core:/core
      - ../plugins:/plugins
      - ../data:/data
    ports: ["8080:8080"]
    command: bash -lc "pip install -e . && uvicorn app.main:app --host 0.0.0.0 --port 8080"

  temporal-worker:
    build: ../services/temporal-worker
    depends_on: [temporal]
    environment:
      - TEMPORAL_HOST=temporal:7233
    volumes:
      - ..:/workspace

volumes:
  n8n_data:
  qdrant_data:
  meili_data:
  pg_data:
  ollama_data:
