global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'temporal-worker'
    static_configs:
      - targets: ['temporal-worker:9109']
  - job_name: 'autoagent-core'
    metrics_path: /metrics
    static_configs:
      - targets: ['autoagent-core:8080']
