apiVersion: 1

groups:
  - orgId: 1
    name: sample
    folder: Alerts
    interval: 1m
    rules:
      - uid: graphite_example
        title: High request rate
        condition: C
        data:
          - refId: A
            datasourceUid: graphite
            model:
              refId: A
              target: stats.counters.requests.count
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              expression: A
              type: reduce
              reducer: last
          - refId: C
            datasourceUid: __expr__
            model:
              refId: C
              expression: B
              type: threshold
              conditions:
                - evaluator:
                    type: gt
                    params: [100]
                  reducer: last
                  type: query
        for: 1m
        annotations:
          summary: High request rate
        labels:
          severity: warning
        noDataState: OK
        execErrState: Alerting
