name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install -e . || true
        pip install pytest requests pdfminer.six pillow httpx
    - name: Run tests
      run: |
        pytest -q core/tests -k 'registry or policy or planning or e2e' || pytest -q core/tests
